export const InvoiceStatus = {
  Draft: 1,
  Issued: 2,
  PartiallyPaid: 3,
  Paid: 4,
  Overdue: 5,
  Cancelled: 6,
} as const;

export type InvoiceStatusValue = (typeof InvoiceStatus)[keyof typeof InvoiceStatus];

export interface InvoiceListDto {
  id: number;
  invoiceNumber: string;
  studentName: string;
  status: InvoiceStatusValue;
  dueDate: string;
  totalAmount: number;
  balanceDue: number;
}

export interface InvoiceItemDto {
  id: number;
  feeTypeId: number;
  feeTypeName: string;
  description: string;
  originalAmount: number;
  discountAmount: number;
  fineAmount: number;
  netAmount: number;
  quantity: number;
  sortOrder: number;
}

export interface InvoiceDto extends InvoiceListDto {
  academicYearId: number;
  academicYearName: string;
  studentId: number;
  studentAdmissionNumber: string;
  feeStructureId?: number | null;
  invoiceDate: string;
  amountPaid: number;
  month?: number | null;
  year?: number | null;
  isAutoGenerated: boolean;
  notes?: string | null;
  cancelledAt?: string | null;
  cancellationReason?: string | null;
  cancelledByEmployeeId?: number | null;
  cancelledByEmployeeName?: string | null;
  items: InvoiceItemDto[];
  createdAt: string;
}

export interface PagedResult<T> {
  items: T[];
  totalCount: number;
  pageNumber: number;
  pageSize: number;
  totalPages: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}

export interface InvoiceFilters {
  pageNumber: number;
  pageSize: number;
  status?: InvoiceStatusValue;
  studentId?: number;
  academicYearId?: number;
}

export interface CreateInvoiceItemDto {
  feeTypeId: number;
  description: string;
  originalAmount: number;
  discountAmount: number;
  fineAmount: number;
  quantity: number;
  sortOrder: number;
}

export interface CreateInvoiceDto {
  studentId: number;
  academicYearId: number;
  feeStructureId?: number | null;
  invoiceDate: string;
  dueDate: string;
  month?: number | null;
  year?: number | null;
  notes?: string | null;
  items: CreateInvoiceItemDto[];
}

export interface CancelInvoiceDto {
  cancellationReason: string;
}

export interface GenerateMonthlyInvoicesDto {
  academicYearId: number;
  month: number;
  year: number;
  schoolClassId?: number | null;
  dueDate: string;
  invoiceDate?: string | null;
}

export interface InvoiceGenerationErrorDto {
  studentId: number;
  studentName: string;
  reason: string;
}

export interface InvoiceGenerationResultDto {
  totalStudentsEvaluated: number;
  invoicesCreated: number;
  skippedAlreadyInvoiced: number;
  skippedNoMonthlyItems: number;
  failed: number;
  errors: InvoiceGenerationErrorDto[];
}

export interface LateFineApplicationResultDto {
  totalInvoicesEvaluated: number;
  invoicesUpdated: number;
  skippedWithinGracePeriod: number;
  skippedNoRule: number;
  failed: number;
  totalFineApplied: number;
  errors: InvoiceGenerationErrorDto[];
}