using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SchoolERP.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SchoolERP.Infrastructure.Persistence.Configurations
{
    public class InvoiceConfiguration : IEntityTypeConfiguration<Invoice>
    {
        public void Configure(EntityTypeBuilder<Invoice> builder)
        {
            builder.ToTable("Invoices");

            // Primary Key
            builder.HasKey(x => x.Id);

            // Properties
            builder.Property(x => x.InvoiceNumber)
                   .IsRequired()
                   .HasMaxLength(50);

            builder.Property(x => x.Status)
                   .IsRequired()
                   .HasConversion<string>()
                   .HasMaxLength(20);

            builder.Property(x => x.InvoiceDate)
                   .IsRequired();

            builder.Property(x => x.DueDate)
                   .IsRequired();

            builder.Property(x => x.TotalAmount)
                   .HasPrecision(18, 2)
                   .HasDefaultValue(0);

            builder.Property(x => x.AmountPaid)
                   .HasPrecision(18, 2)
                   .HasDefaultValue(0);

            builder.Property(x => x.BalanceDue)
                   .HasPrecision(18, 2)
                   .HasDefaultValue(0);

            builder.Property(x => x.IsAutoGenerated)
                   .HasDefaultValue(false);

            builder.Property(x => x.Notes)
                   .HasMaxLength(500);

            builder.Property(x => x.CancellationReason)
                   .HasMaxLength(300);

            // Optimistic Concurrency
            builder.Property(x => x.RowVersion)
                   .IsRowVersion();

            // Relationships
            builder.HasOne(x => x.Student)
                   .WithMany(x => x.Invoices)
                   .HasForeignKey(x => x.StudentId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(x => x.AcademicYear)
                   .WithMany(x => x.Invoices)
                   .HasForeignKey(x => x.AcademicYearId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(x => x.FeeStructure)
                   .WithMany(x => x.Invoices)
                   .HasForeignKey(x => x.FeeStructureId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasMany(x => x.InvoiceItems)
                   .WithOne(x => x.Invoice)
                   .HasForeignKey(x => x.InvoiceId)
                   .OnDelete(DeleteBehavior.Cascade);

            builder.HasMany(x => x.Payments)
                   .WithOne(x => x.Invoice)
                   .HasForeignKey(x => x.InvoiceId)
                   .OnDelete(DeleteBehavior.Restrict);

            // Unique Index
            builder.HasIndex(x => x.InvoiceNumber)
                   .IsUnique()
                   .HasDatabaseName("IX_Invoices_InvoiceNumber");
            // InvoiceConfiguration.cs — ADD
            builder.HasOne(x => x.CancelledByEmployee)
                   .WithMany()
                   .HasForeignKey(x => x.CancelledByEmployeeId)
                   .OnDelete(DeleteBehavior.Restrict);
            // Prevent Duplicate Billing
            builder.HasIndex(x => new
            {
                x.StudentId,
                x.AcademicYearId,
                x.Month,
                x.Year,
                x.FeeStructureId
            })
            .IsUnique()
            .HasFilter("[FeeStructureId] IS NOT NULL")
            .HasDatabaseName("IX_Invoices_Student_Period_FeeStructure");
          
            // Performance Indexes
            builder.HasIndex(x => x.StudentId)
                   .HasDatabaseName("IX_Invoices_StudentId");

            builder.HasIndex(x => x.AcademicYearId)
                   .HasDatabaseName("IX_Invoices_AcademicYearId");

            builder.HasIndex(x => x.Status)
                   .HasDatabaseName("IX_Invoices_Status");

            builder.HasIndex(x => x.InvoiceDate)
                   .HasDatabaseName("IX_Invoices_InvoiceDate");

            builder.HasIndex(x => x.DueDate)
                   .HasDatabaseName("IX_Invoices_DueDate");
           
        }
    }
}
