using AutoMapper;
using FluentValidation;
using SchoolERP.Application.Common.Exceptions;
using SchoolERP.Application.Common.Interfaces;
using SchoolERP.Application.Common.Interfaces.Services;
using SchoolERP.Application.Features.Invoice.DTOs;
using SchoolERP.Application.Features.Invoice.Interfaces;
using SchoolERP.Domain.Entities;
using SchoolERP.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SchoolERP.Infrastructure.Services
{
    public class InvoiceService : IInvoiceService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly ICurrentEmployeeService _currentEmployee;
        private readonly IValidator<CreateInvoiceDto> _createValidator;
        private readonly IValidator<CancelInvoiceDto> _cancelValidator;

        public InvoiceService(
            IUnitOfWork unitOfWork, IMapper mapper, ICurrentEmployeeService currentEmployee,
            IValidator<CreateInvoiceDto> createValidator, IValidator<CancelInvoiceDto> cancelValidator)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _currentEmployee = currentEmployee;
            _createValidator = createValidator;
            _cancelValidator = cancelValidator;
        }

        public async Task<(IReadOnlyList<InvoiceListDto> Items, int TotalCount)> GetPagedAsync(
            int pageNumber, int pageSize, InvoiceStatus? status, int? studentId, int? academicYearId,
            CancellationToken cancellationToken = default)
        {
            var (invoices, total) = await _unitOfWork.InvoiceRepository.GetPagedAsync(
                pageNumber, pageSize, status, studentId, academicYearId, cancellationToken);
            return (_mapper.Map<IReadOnlyList<InvoiceListDto>>(invoices), total);
        }

        public async Task<InvoiceDto?> GetByIdAsync(int id, CancellationToken cancellationToken = default)
        {
            var invoice = await _unitOfWork.InvoiceRepository.GetWithDetailsAsync(id, cancellationToken);
            return invoice is null ? null : _mapper.Map<InvoiceDto>(invoice);
        }

        public async Task<IReadOnlyList<InvoiceListDto>> GetByStudentIdAsync(int studentId, CancellationToken cancellationToken = default)
        {
            var invoices = await _unitOfWork.InvoiceRepository.GetByStudentIdAsync(studentId, cancellationToken);
            return _mapper.Map<IReadOnlyList<InvoiceListDto>>(invoices);
        }

        public async Task<InvoiceDto> CreateAsync(CreateInvoiceDto request, CancellationToken cancellationToken = default)
        {
            var validation = await _createValidator.ValidateAsync(request, cancellationToken);
            if (!validation.IsValid) throw new ValidationException(validation.Errors);

            // Item-level NetAmount = Original - Discount + Fine (business formula, service এ compute করা হয়, DTO/mapping এ না)
            var items = request.Items.Select(i => new InvoiceItem
            {
                FeeTypeId = i.FeeTypeId,
                Description = i.Description,
                OriginalAmount = i.OriginalAmount,
                DiscountAmount = i.DiscountAmount,
                FineAmount = i.FineAmount,
                NetAmount = i.OriginalAmount - i.DiscountAmount + i.FineAmount,
                Quantity = i.Quantity,
                SortOrder = i.SortOrder
            }).ToList();

            var totalAmount = items.Sum(i => i.NetAmount * i.Quantity);

            var invoiceNumber = await GenerateInvoiceNumberAsync(request.AcademicYearId, cancellationToken);

            var invoice = new SchoolERP.Domain.Entities.Invoice
            {
                InvoiceNumber = invoiceNumber,
                AcademicYearId = request.AcademicYearId,
                StudentId = request.StudentId,
                FeeStructureId = request.FeeStructureId,
                Status = InvoiceStatus.Issued,
                InvoiceDate = request.InvoiceDate,
                DueDate = request.DueDate,
                Month = request.Month,
                Year = request.Year,
                TotalAmount = totalAmount,
                AmountPaid = 0,
                BalanceDue = totalAmount,
                IsAutoGenerated = false,
                Notes = request.Notes,
                InvoiceItems = items
            };

            await _unitOfWork.InvoiceRepository.AddAsync(invoice, cancellationToken);
            await _unitOfWork.SaveChangesAsync(cancellationToken);

            var created = await _unitOfWork.InvoiceRepository.GetWithDetailsAsync(invoice.Id, cancellationToken);
            return _mapper.Map<InvoiceDto>(created);
        }

        public async Task<InvoiceDto> CancelAsync(int id, CancelInvoiceDto request, CancellationToken cancellationToken = default)
        {
            var validation = await _cancelValidator.ValidateAsync(request, cancellationToken);
            if (!validation.IsValid) throw new ValidationException(validation.Errors);

            var employeeId = await _currentEmployee.GetIdAsync(cancellationToken);

            var invoice = await _unitOfWork.InvoiceRepository.GetTrackedWithItemsAsync(id, cancellationToken)
        ?? throw new NotFoundException(nameof(SchoolERP.Domain.Entities.Invoice), id);

            // Business rule: Do not allow cancellation after payments have been collected.
            // A refund process is required, which is not currently implemented.
            if (invoice.AmountPaid > 0)
                throw new BadRequestException("Cannot cancel an invoice that already has payments recorded. Void the payments first.");

            if (invoice.Status == InvoiceStatus.Cancelled)
                throw new BadRequestException("Invoice is already cancelled.");

            invoice.Status = InvoiceStatus.Cancelled;
            invoice.CancelledAt = DateTime.UtcNow;
            invoice.CancellationReason = request.CancellationReason;
            invoice.CancelledByEmployeeId = employeeId;
            
            // Optimistic concurrency using RowVersion.
            // If another user has already modified this invoice before SaveChangesAsync
            // (for example, while a payment is being processed), EF Core will throw
            // a DbUpdateConcurrencyException.
            try
            {
                await _unitOfWork.SaveChangesAsync(cancellationToken);
            }
            catch (Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException)
            {
                throw new ConflictException("This invoice was modified by another user. Please refresh and try again.");
            }

            var updated = await _unitOfWork.InvoiceRepository.GetWithDetailsAsync(id, cancellationToken);
            return _mapper.Map<InvoiceDto>(updated!);
        }

        /// <summary>Format: INV-{AcademicYearName}-{6-digit sequence}, e.g. INV-2025-2026-000123</summary>
        private async Task<string> GenerateInvoiceNumberAsync(int academicYearId, CancellationToken cancellationToken)
        {
            var lastNumber = await _unitOfWork.InvoiceRepository.GetLastInvoiceNumberAsync(academicYearId, cancellationToken);

            int nextSequence = 1;
            if (!string.IsNullOrEmpty(lastNumber))
            {
                var parts = lastNumber.Split('-');
                if (parts.Length > 0 && int.TryParse(parts[^1], out var lastSeq))
                    nextSequence = lastSeq + 1;
            }

            var academicYear = await _unitOfWork.AcademicYearRepository.GetByIdAsync(academicYearId, cancellationToken);
            var yearPart = academicYear?.Name.Replace(" ", "").Replace("/", "-") ?? DateTime.UtcNow.Year.ToString();

            return $"INV-{yearPart}-{nextSequence:D6}";
        }
    }
}
