using SchoolERP.Domain.Common;
using SchoolERP.Domain.Entities;
using SchoolERP.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SchoolERP.Domain.Entities
{
    public class Invoice : BaseEntity
    {
        public string InvoiceNumber { get; set; } = string.Empty;

        public int AcademicYearId { get; set; }
        public AcademicYear AcademicYear { get; set; } = null!;

        public int StudentId { get; set; }
        public Student Student { get; set; } = null!;

        public int? FeeStructureId { get; set; }
        public FeeStructure? FeeStructure { get; set; }

        public InvoiceStatus Status { get; set; } = InvoiceStatus.Draft;

        public DateTime InvoiceDate { get; set; }
        public DateTime DueDate { get; set; }

        public int? Month { get; set; }
        public int? Year { get; set; }

        public decimal TotalAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal BalanceDue { get; set; }
        public string? Notes { get; set; }
        /// <summary>True if generated by the monthly background job rather than manually.</summary>
        public bool IsAutoGenerated { get; set; } = false;
        public DateTime? CancelledAt { get; set; }
        public string? CancellationReason { get; set; }
        public int? CancelledByEmployeeId { get; set; }
        public Employee? CancelledByEmployee { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
        public ICollection<InvoiceItem> InvoiceItems { get; set; } = new List<InvoiceItem>();
        public ICollection<Payment> Payments { get; set; } = new List<Payment>();
      
    }
}
