using SchoolERP.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SchoolERP.Application.Features.Invoice.DTOs
{

    /// <summary>
    /// Full invoice detail response model.
    /// </summary>
    public class InvoiceDto
    {
        public int Id { get; set; }

        public string InvoiceNumber { get; set; } = string.Empty;


        public int AcademicYearId { get; set; }

        public string AcademicYearName { get; set; } = string.Empty;


        public int StudentId { get; set; }

        public string StudentName { get; set; } = string.Empty;

        public string StudentAdmissionNumber { get; set; } = string.Empty;


        public int? FeeStructureId { get; set; }


        public InvoiceStatus Status { get; set; }


        public DateTime InvoiceDate { get; set; }

        public DateTime DueDate { get; set; }


        public int? Month { get; set; }

        public int? Year { get; set; }


        public decimal TotalAmount { get; set; }

        public decimal AmountPaid { get; set; }

        public decimal BalanceDue { get; set; }


        public bool IsAutoGenerated { get; set; }


        public string? Notes { get; set; }


        public DateTime? CancelledAt { get; set; }

        public string? CancellationReason { get; set; }

        public int? CancelledByEmployeeId { get; set; }
        public string? CancelledByEmployeeName { get; set; }
        public List<InvoiceItemDto> Items { get; set; } = new();


        public DateTime CreatedAt { get; set; }
    }
    /// <summary>
    /// Read model for invoice line item.
    /// </summary>
    public class InvoiceItemDto
    {
        public int Id { get; set; }

        public int FeeTypeId { get; set; }

        public string FeeTypeName { get; set; } = string.Empty;


        public string Description { get; set; } = string.Empty;


        public decimal OriginalAmount { get; set; }

        public decimal DiscountAmount { get; set; }

        public decimal FineAmount { get; set; }

        public decimal NetAmount { get; set; }


        public int Quantity { get; set; }

        public int SortOrder { get; set; }
    }
}
