/**
 * Frontend mirror of backend PermissionNames constants.
 * Keep in sync with SchoolERP.Domain.Constants.PermissionNames.
 */
export const Permission = {
  StudentView: "Student.View",
  StudentCreate: "Student.Create",
  TeacherView: "Teacher.View",
  EmployeeView: "Employee.View",
  EmployeeCreate: "Employee.Create",
  EmployeeEdit: "Employee.Edit",
  EmployeeDelete: "Employee.Delete",
  DesignationView: "Designation.View",
  UserView: "User.View",
  GuardianView: "Guardian.View",
  GuardianCreate: "Guardian.Create",
  InvoiceView: "Invoice.View",
  InvoiceCreate: "Invoice.Create",
  InvoiceCancel: "Invoice.Cancel",
  FeeCategoryView: "FeeCategory.View",
  FeeCategoryCreate: "FeeCategory.Create",
  FeeCategoryEdit: "FeeCategory.Edit",
  FeeCategoryDelete: "FeeCategory.Delete",
  FeeTypeView: "FeeType.View",
  FeeTypeCreate: "FeeType.Create",
  FeeTypeEdit: "FeeType.Edit",
  FeeTypeDelete: "FeeType.Delete",
  FeeStructureView: "FeeStructure.View",
  FeeStructureCreate: "FeeStructure.Create",
  FeeStructureEdit: "FeeStructure.Edit",
  FeeStructureDelete: "FeeStructure.Delete",
  ConcessionView: "Concession.View",
  ConcessionCreate: "Concession.Create",
  ConcessionEdit: "Concession.Edit",
  ConcessionApprove: "Concession.Approve",
  ConcessionDelete: "Concession.Delete",
  PaymentView: "Payment.View",
  PaymentCollect: "Payment.Collect",
  PaymentVoid: "Payment.Void",
  ReceiptView: "Receipt.View",
  ReceiptVoid: "Receipt.Void",
  LateFineRuleView: "LateFineRule.View",
  LateFineRuleManage: "LateFineRule.Manage",
  FeeReportView: "FeeReport.View",
  SchoolView: "School.View",
  SchoolCreate: "School.Create",
  SchoolUpdate: "School.Edit",
  SchoolDelete: "School.Delete",
  AttendanceReportView: "AttendanceReport.View",
  StudentAttendanceView: "StudentAttendance.View",
  StudentAttendanceCreate: "StudentAttendance.Create",
  StudentAttendanceEdit: "StudentAttendance.Edit",
  EmployeeAttendanceView: "EmployeeAttendance.View",
  EmployeeAttendanceCreate: "EmployeeAttendance.Create",
  EmployeeAttendanceEdit: "EmployeeAttendance.Edit",
  NoticeView: "Notice.View",
  ExamView: "Exam.View",
  ExamCreate: "Exam.Create",
  ExamEdit: "Exam.Edit",
  ExamDelete: "Exam.Delete",
  ExamPublish: "Exam.Publish",
  ExamComplete: "Exam.Complete",
  ExamCancel: "Exam.Cancel",
  ExamTypeView: "ExamType.View",
  ExamTypeCreate: "ExamType.Create",
  ExamTypeEdit: "ExamType.Edit",
  ExamTypeDelete: "ExamType.Delete",
  ExamScheduleView: "ExamSchedule.View",
  ExamScheduleCreate: "ExamSchedule.Create",
  ExamScheduleEdit: "ExamSchedule.Edit",
  ExamScheduleDelete: "ExamSchedule.Delete",
  GradeSetupView: "GradeSetup.View",
  GradeSetupManage: "GradeSetup.Manage",
  WeightSetupView: "WeightSetup.View",
  WeightSetupManage: "WeightSetup.Manage",
  MarksEntryView: "MarksEntryView",
  MarksEntryCreate: "MarksEntryCreate",
  MarksEntryEdit: "MarksEntryEdit",
  MarksEntryPublish: "MarksEntryPublish",
  ResultView: "ResultView",
  ResultCalculate: "ResultCalculate",
  ResultPublish: "ResultPublish",
  ResultUnlock: "ResultUnlock",
  ResultAuditView: "ResultAuditView",
  FinalResultView: "FinalResultView",
  FinalResultCalculate: "FinalResultCalculate",
  FinalResultPublish: "FinalResultPublish",
  FinalResultUnlock: "FinalResultUnlock",
  TranscriptView: "TranscriptView",
  AcademicYearView: "AcademicYear.View",
  SchoolClassView: "SchoolClassView",
  SchoolClassCreate: "SchoolClassCreate",
  SchoolClassEdit: "SchoolClassEdit",
  SchoolClassDelete: "SchoolClassDelete",
  SectionView: "SectionView",
  SectionCreate: "SectionCreate",
  SectionEdit: "SectionEdit",
  SectionDelete: "SectionDelete",
  SubjectView: "SubjectView",
  SubjectCreate: "SubjectCreate",
  SubjectEdit: "SubjectEdit",
  SubjectDelete: "SubjectDelete",
  SubjectTeacherView: "SubjectTeacherView",
  SubjectTeacherAssign: "SubjectTeacherAssign",
  SubjectTeacherRemove: "SubjectTeacherRemove",
  ClassSubjectView: "ClassSubjectView",
  ClassSubjectAssign: "ClassSubjectAssign",
  ClassSubjectRemove: "ClassSubjectRemove",
  ProgressReportView: "ProgressReport.View",
} as const;

export type PermissionName = (typeof Permission)[keyof typeof Permission];

export const AppRole = {
  Admin: "Admin",
  Teacher: "Teacher",
  Student: "Student",
  Accountant: "Accountant",
} as const;

export type AppRoleName = (typeof AppRole)[keyof typeof AppRole];
